embed_assets    : off
# todo: turning packaging and compression off, unntil we fix it
package_assets  : off
compress_assets : off

javascripts:
  common:
    - public/javascripts/libs/jquery.js
    - public/javascripts/libs/jquery.expander.min.js
    - public/javascripts/libs/less.js
    - public/stylesheets/bootstrap/js/bootstrap.min.js
    - public/javascripts/libs/underscore.js
    - public/javascripts/libs/backbone.js
    - public/javascripts/libs/backbone_rails_sync.js
    - public/javascripts/libs/*.js
    - public/javascripts/app/**/*.js
    - public/javascripts/application.js
    - public/javascripts/jquery_ujs.js
    - app/views/**/*.jst