embed_assets: on

javascripts:
  common:
    - public/javascripts/libs/jquery.js
    - public/javascripts/libs/less.js
    - public/javascripts/bootstrap.min.js
    - public/javascripts/libs/underscore.js
    - public/javascripts/libs/backbone.js
    - public/javascripts/libs/backbone_rails_sync.js
    - public/javascripts/libs/*.js
    - public/javascripts/app/**/*.js
    - public/javascripts/application.js
    - app/views/**/*.jst

stylesheets:
  common:
    - public/stylesheets/bootstrap/bootstrap.less
    - public/stylesheets/site.less